//
//  BMStrings.swift
//  Bastian Morath
//
//  Created by Bastian Morath on 23/04/15.
//  Copyright (c) 2015 Bastian Morath. All rights reserved.
//

import UIKit
struct BMStrings{
    static let aboutMyselfString = "Hi, my name is Bastian Morath. I’m a 20-years-old student from Zurich, Switzerland. I’m living with my mom, my twin-brother and my little brother in an apartment in Greifensee, a beautiful place right next to an ancient castle and a lake, which gives me  bit of variety to my technological life at home!"

    static let photographyString = "I do a lot of photography in my free time. I like to go out in the nature with friends and discover nice places to take pictures. For me it’s another good balance to my programming at home, as I sometimes just need some variety! "

    static let travelingString = "The world is a book, and those who do not travel read only a page.\n      - Saint Augustine\n\nTraveling is a big part in my life. I love discovering other cultures and meeting interesting people around the world. I think that’s a wonderful way to get another perspective to look at the world, and I built a lot of relationships that will last forever. I met developers and entrepreneurs from Switzerland, France, Germany, California and Florida and it was interesting to share my thoughts with them. I was told that San Francisco is a beautiful city, so that would be a perfect opportunity  to me to visit that place!"

    static let sportsString = "Sports give me a very good balance to school and programming where I mostly sit indoors on a chair. The sport that I’m most passionate about is European handball. I’ve been playing it for more than 12 years! The game is very fast and includes body-contact, fortunately I haven’t had a major injury yet! Apart from this team-sport, I also play golf, parkour, slackline and basketball occasionally."

    static let educationString = "I attended three different Elementary school because we moved three times. We then finally found a wonderful place called Greifensee, a little outskirt of Zurich. I then chose a scientific & mathematic high school in Uster, which normally lasts 6 years in Switzerland. In my 5th year, I went to the North-West of France for 3 months with an exchange program called AFS. It was a wonderful experienced and I learned a lot of new things. \n\n Also in my 5th year, I could participate in a program of the swiss endowment called “Schweizer Jugend Forscht” (Swiss Youth researches) at the University of Fribourg. I build a program to automatically control trains. In my senior year, my twin brother and I developed an application and we were invited by the University of Zurich to present it with a poster!\n\nAfter Highschool, I had to go to military for 6 months, it’s mandatory in Switzerland. It was a very good life experience and it was a very defining part of my life, as I learned a lot that will help me later in life. I then went to California for 6 months to practise my English. I spend my time at a school in Santa Maria and I’m still enjoying it very much in this beautiful state! I applied to the ETH  University in Zurich, where I’m currently enrolled. If possible, I want to do an internship in California as a iOS-Developer and then do my masters in the same state! "

    static let codingString = "“There’s an app for that!”\n\nSince the first day I had an Apple product - it was an iMac - I admired its simple, but at least as stunning design. It was in 2008 when my parents gave me an iPhone 3G and when I - and a lot of other people too - was first introduced into the world of smartphones. First I’ve just seen it from the perspective of a consumer. But as I grew older and became more reasonable, I was more and more interested in what I can do with it and how applications work behind the scenes. There were so many cool applications in the App Store, but there were also some that I didn’t like at all - mostly because of its design. I thought  it would be great to learn programming so I could program my applications on my phone as I want them to be! But unfortunately it wasn’t that easy. Becoming a programmer takes a lot of hard work. I started programming Logo and Java  at high school, but it was more about algorithms than useful applications in life.\n\nIt was a project at high school where I first developed an iOS-Application, with focus on user experience and simplicity, from scratch - search for an idea, define a concept, designing a User Interface, the implementation and testing. I really like all of these steps, not just the coding  part, as all of them are equal important in order to develop an outstanding application! It was a groundbreaking decision for me to do something in the field of computer science, as a lot of my time in the following years was dedicated to application development! My brother and I were even invited to the ETH (University of Zurich) to present our app!"

    static let guitarString = "I’ve been playing the guitar for more than 10 years and I’m still passionate about it. It's a way for me to escape stress and the sometimes hectic time from work and school, and it teaches me to pay attention to details, as you can hear every single mistake you play."

    static let myMarksString = "MyMarks was my first iOS-Application that I developed with my twin-brother. With MyMarks, you can easily manage your marks. It has a beautiful design and it’s simple to use. You can calculate averages, export your marks and we are currently working on a huge update coming soon!"

    static let antumString = "In my Junior year, two friends of mine and I decided to found a company and develop a platform for student to improve their way of learning. We wanted the students to have their school material like notes, books, exams and summaries, always with them, on their smartphone. Users could create a new content - text, pictures, videos, multiple-choices and audio - and share it with their friends.                  We met up every week and I worked for at least 10 hours a week for this start up next to my normal classes. It was a hard time but I experienced a lot and learned to work and program in a team. Unfortunately, after about an year, I had to go to military service in Switzerland, as it is mandatory. I didn’t have time at all anymore to participate in that company, but they continued to work at it and will soon launch a first version! I’m very proud to have been part of that amazing team!"

    static let lociString = "Loci was born in a Hackathon of some friends and me. We discussed a couple of ideas but ended up doing something with “Sharing Locations”. We created an application with the main focus on sharing users location for a certain amount of time with friends, tracking their location if they allow it and creating a statistics of your most visited places. We couldn’t finish it in our planned 36 hours, as we were all kind of a perfectionist and didn't want to submit an in our opinion unfinished application!"

    static let mintString = "MINT ( acronym for the german words mathematics, computer science, science and technology) was a school-project and included building a website for students to access interesting articles about these four subjects. It was interesting for me to do something non iOS related, but I actually see myself more in iOS than web programming!"
}

